version: "3.8"

services:
    django:
        build: .
        container_name: django
        command: >
            sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            POSTGRES_DB: ${NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata: